before_script:
  - export http_proxy=http://sjc1intproxy01.crd.ge.com:8080/
  - export https_proxy=http://sjc1intproxy01.crd.ge.com:8080/
  - export no_proxy="localhost, 127.0.0.1, *.ge.com"
  - git config --global http.sslVerify "false"
  - git config --global http.proxy http://sjc1intproxy01.crd.ge.com:8080
  - git config --global https.proxy http://sjc1intproxy01.crd.ge.com:8080
  - npm config set proxy http://sjc1intproxy01.crd.ge.com:8080/
  - npm config set https-proxy http://sjc1intproxy01.crd.ge.com:8080/
  - export JAVA_HOME=/usr/local/java/jdk1.7.0_60
  - export PATH=$PATH:/activator-1.2.10:$JAVA_HOME/bin

script:
  - node -v
  - npm -v
  - grunt -V
  - npm install
  - bower --allow-root install
  - grunt update
  - activator test
  - grunt -v
  - activator -v dist

