before_script:
  - export http_proxy=http://sjc1intproxy01.crd.ge.com:8080/
  - export https_proxy=http://sjc1intproxy01.crd.ge.com:8080/
  - export no_proxy="localhost, 127.0.0.1, *.ge.com"
  - git config --global http.sslVerify "false"
  - git config --global http.proxy http://sjc1intproxy01.crd.ge.com:8080
  - git config --global https.proxy http://sjc1intproxy01.crd.ge.com:8080
  - npm config set proxy http://sjc1intproxy01.crd.ge.com:8080/
  - npm config set https-proxy http://sjc1intproxy01.crd.ge.com:8080/

script:
  - npm config delete proxy
  - npm config delete https-proxy
  - npm config set registry http://GIS05808.devcloud.ge.com:9095  
  - npm cache clean  
  - node -v
  - npm -v
  - npm install
  - bower --allow-root install
  - grunt update
  - grunt -v
